INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('Sherlock film', '12 jaar en ouder', 'Engels', '01:29');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '12 jaar en ouder', 'Engels', '01:34');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '16 jaar en ouder', 'Engels-Amerikaans', '02:34');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '18 jaar en ouder', 'Nederlands', '01:20');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '16 jaar en ouder', 'Engels-Amerikaans', '01:39');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '12 jaar en ouder', 'Engels-Amerikaans', '02:41');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '16 jaar en ouder', 'Engels-Amerikaans', '01:43');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '6 jaar en ouder', 'Nederlands', '01:37');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '6 jaar en ouder', 'Duits', '02:58');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '12 jaar en ouder', 'Vlaams', '01:48');
INSERT INTO netflixx.dbo.film (film, Leeftijd, Taal, Tijdsduur) VALUES ('film', '16 jaar en ouder', 'Engels', '02:16');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (1002, '12 jaar en ouder', 'Engels', 'Detective', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (1003, '12 jaar en ouder', 'Engels', 'Detective', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (1004, '12 jaar en ouder', 'Engels', 'Detective', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (1005, '12 jaar en ouder', 'Engels', 'Detective', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (1006, '12 jaar en ouder', 'Engels', 'Detective', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (1007, '12 jaar en ouder', 'Engels', 'Detective', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (1008, '12 jaar en ouder', 'Engels', 'Detective', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (1009, '12 jaar en ouder', 'Engels', 'Detective', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2000, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2001, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2002, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2003, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2004, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2005, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2006, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2007, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2008, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2009, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2010, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2011, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2012, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2013, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2014, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2015, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2016, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2017, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2018, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (2019, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Fargo');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3001, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3002, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3003, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3004, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3005, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3006, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3007, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3008, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3009, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3010, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'Breaking Bad');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3101, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3102, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3103, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3105, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3104, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3106, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3107, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3109, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3110, '16 jaar en ouder', 'Engels-Amerikaans', 'Spanning', 'NULL');
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3111, '16 jaar of ouder', 'English', 'Fantasy', null);
INSERT INTO netflixx.dbo.persoon (Id, Leeftijd, Taal, Genre, [lijkt een beetje op]) VALUES (3112, '16 jaar of ouder', 'English', 'Fantasy', null);
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (1, 1001, 1, 'A Study in Pink', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (1, 1002, 2, 'The Blind Banker', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (1, 1003, 3, 'The Great Game', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (2, 1004, 1, 'A Scandal in Belgravia', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (2, 1005, 2, 'The Hounds of Baskerville', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (2, 1006, 3, 'The Reichenbach Fall', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (3, 1007, 1, 'The Empty Hearse', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (3, 1008, 2, 'The Sign of Three', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (3, 1009, 3, 'His Last Vow', '01:28');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (4, 2000, 1, 'Pilot', '00:58');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (4, 2001, 2, 'Cat’s in the Bag…', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (4, 2002, 3, '…And the Bag’s in the River', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (4, 2003, 4, 'Cancer Man', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (4, 2004, 5, 'Gray Matter', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (4, 2005, 6, 'Crazy Handful of Nothin’', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (4, 2006, 7, 'A No-Rough-Stuff-Type Deal', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2007, 1, 'Seven Thirty-Seven', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2008, 2, 'Grilled', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2009, 3, 'Bit by a Dead Bee', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2010, 4, 'Down', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2011, 5, 'Breakage', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2012, 6, 'Peekaboo', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2013, 7, 'Negro Y Azul', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2014, 8, 'Better Call Saul', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2015, 9, '4 Days Out', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2016, 10, 'Over', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2017, 11, 'Mandala', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2018, 12, 'Phoenix', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (5, 2019, 13, 'ABQ', '00:48');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3001, 1, 'The Crocodile''s Dilemma', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3002, 2, 'The Rooster Prince', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3003, 3, 'A Muddy Road', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3004, 4, 'Eating the Blame', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3005, 5, 'The Six Ungraspables', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3006, 6, 'Buridan''s Ass', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3007, 7, 'Who Shaves the Barber?', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3008, 8, 'The Heap', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3009, 9, 'A Fox, a Rabbit, and a Cabbage', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (6, 3010, 10, 'Morton''s Fork', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3101, 1, 'Waiting for Dutch', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3102, 1, 'Before the Law', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3103, 1, 'The Myth of Sisyphus', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3104, 1, 'Fear and Trembling', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3105, 1, 'The Gift of the Magi', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3106, 1, 'Rhinoceros', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3107, 1, 'Did you do this? No, you did it!', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3108, 1, 'Loplop', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3109, 1, 'The Castle', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (7, 3110, 1, 'Palindrome', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (2, 3111, 1, 'Fear and Trembling', '01:08');
INSERT INTO netflixx.dbo.seizoen (seizoenId, Id, Aflevering, Titel, Tijdsduur) VALUES (2, 3112, 1, 'Before the Law', '01:08');
INSERT INTO netflixx.dbo.seizoen_serie (SerieID, Seizoen, SeizoenID) VALUES (1, 1, 1);
INSERT INTO netflixx.dbo.seizoen_serie (SerieID, Seizoen, SeizoenID) VALUES (1, 2, 2);
INSERT INTO netflixx.dbo.seizoen_serie (SerieID, Seizoen, SeizoenID) VALUES (1, 3, 3);
INSERT INTO netflixx.dbo.seizoen_serie (SerieID, Seizoen, SeizoenID) VALUES (2, 1, 4);
INSERT INTO netflixx.dbo.seizoen_serie (SerieID, Seizoen, SeizoenID) VALUES (2, 2, 5);
INSERT INTO netflixx.dbo.seizoen_serie (SerieID, Seizoen, SeizoenID) VALUES (3, 1, 6);
INSERT INTO netflixx.dbo.seizoen_serie (SerieID, Seizoen, SeizoenID) VALUES (3, 2, 7);
INSERT INTO netflixx.dbo.serie (serieID, serie) VALUES (1, 'Sherlock');
INSERT INTO netflixx.dbo.serie (serieID, serie) VALUES (2, 'Breaking Bad');
INSERT INTO netflixx.dbo.serie (serieID, serie) VALUES (3, 'Fargo');